### ISSUE TITLE
HW1

### ISSUE THREAD

**Issue by nsuvorov17** [BestPracticeSchool/BPS-BaseProgramming_2_2019#1]
Нарожный Никита Федорович
github.com/nsuvorov17/BPS

**Comment by BestPracticeSchool** [comment]
В task1 обрати внимание на **вывод**. Все должно совпадать в точности до пробела. Сейчас у тебя не проходят тесты в task1 именно из-за неверного вывода.

**Comment by BestPracticeSchool** [comment]
В task4 также проблема с выводом. Обрати внимание, что при перечислении аргументов в print() питон их разграничивает пробелами. И попробуй сделать это в виде фукнции (она понадобится в дальнейшем)

```
def NOD (A,B):
      .....
      return c

```

**Comment by BestPracticeSchool** [comment]
В task5 проверь случай **0 0 1**, что-то нам подсказывает, что будет нечто внезапное:)

**Comment by vlasove** [comment]
task1 --- 10/10

**Comment by vlasove** [comment]
task2 --- 12/12

**Comment by vlasove** [comment]
task3 --- 15/15

**Comment by vlasove** [comment]
task4 --- 17/17 
Маленькое замечание --- тут не нужен else. Лишний код

**Comment by vlasove** [comment]
task5 --- неверный вывод. Обрати внимание на регистр символов в ответе. Обрати также внимание, что выводится в примере в случае, если корни отсуствуют

**Comment by nsuvorov17** [comment]
Исправил task5, изменил регистр и заодно убрал пробелы в выводе, пришлось преобразовывать integer в string, сделал вывод в случае, где корни отсутствуют, как в примере.

**Comment by vlasove** [comment]
task5 ---  неверный ответ. Рассмотри случай **0 0 1**

**Comment by nsuvorov17** [comment]
Исправил!

**Comment by vlasove** [comment]
task5 --- 10/10

**Comment by vlasove** [comment]
Да ты могешь!

**BestPractice гордится тобой!**
