### ISSUE TITLE
Burlakov Denis

### ISSUE THREAD

**Issue by HappDen** [BestPracticeSchool/BPS-BaseProgramming_2_2019#2]
https://github.com/HappDen/HW1

**Comment by vlasove** [comment]
task1 --- 10/10

**Comment by vlasove** [comment]
task 2 ---- 12/12

**Comment by vlasove** [comment]
task3 --- неверное решение. Проверь случай 5 4 3

**Comment by vlasove** [comment]
task 4 --- 17/17

**Comment by vlasove** [comment]
task5 --- неверный формат вывода. Обрати внимание, как осуществляется вывод в условии данной задачи.
task5 ---- почему при 0 -2 0 у тебя ответ --0? Один минус я бы еще понял, но два зачем?

**Comment by HappDen** [comment]
Fixed

**Comment by BestPracticeSchool** [comment]
task3 --- 15/15

**Comment by BestPracticeSchool** [comment]
task5 --- 10/10

**Comment by BestPracticeSchool** [comment]
Красавчик!

**BestPractice гордится тобой!**
