### ISSUE TITLE
HW1 Романов Дмитрий

### ISSUE THREAD

**Issue by vlasove** [BestPracticeSchool/BPS-BaseProgramming_2_2019#3]
https://github.com/Dmitriy221/Amber9/tree/master

**Comment by vlasove** [comment]
task1 --- 10/10

**Comment by vlasove** [comment]
task2 --- 12/12

**Comment by vlasove** [comment]
task3 --- 15/15

**Comment by vlasove** [comment]
task4 --- неверный формат вывода. Обрати внимание на лишний пробел в твоем выводе ответа

**Comment by vlasove** [comment]
task5 --- неверный формат вывода. Посмотри, какой формат вывода должен быть у этой задачи в примерах работы данной программы (приведено в условии к этой задаче).

**Comment by Dmitriy221** [comment]
Убрал лишний пробел в task4, исправил формат вывода в task5.
Готово.

**Comment by vlasove** [comment]
task4 --- неверный формат вывода. ``` print("NOD:",a)``` Такая конструкция будет печатать ```NOD: 5``` ,а нужно ```NOD:5```

**Comment by vlasove** [comment]
task5 --- неверный формат вывода.
Строка ```print("X1=:", x)``` совершенно точно не попадает под требуемый вывод.

**Comment by vlasove** [comment]
task4 --- 17/17

**Comment by vlasove** [comment]
task5 --- 10/10

**Comment by vlasove** [comment]
Красавчик!!!

**BestPractice гордится тобой!**
